<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-04B1LE1H" ignored="0" name="Login Test" tests="3" failures="1" timestamp="2023-05-06T11:36:49 BST" time="0.088" errors="0">
  <testcase name="test1" time="0.008" classname="com.nopcommerce.demo.testng.TestNGListenersDemo"/>
  <testcase name="test2" time="0.002" classname="com.nopcommerce.demo.testng.TestNGListenersDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.nopcommerce.demo.testng.TestNGListenersDemo.test2(TestNGListenersDemo.java:22)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.nopcommerce.demo.testng.TestNGListenersDemo">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Login Test -->
